### PR TITLE
feat: support visual editing

### PR DESCRIPTION
**Pull request by rdunk**
This PR provides a method for implementing Sanity visual editing in Nuxt applications.

#### Current Progress

- [x] Support visual editing using `useSanityQuery` and CSM
- [X] Support "basic" visual editing using `useAsyncData` and `client.fetch`
- [X] Update playground
- [X] Update tests
- [x] Update documentation

### CODE REVIEW

**Comment by rdunk** [comment]
Looks like the type tests are failing, the generated `RuntimeConfig` and `PublicRuntimeConfig` override those declared in `index.d.ts`.

Potentially relevant issue: https://github.com/nuxt/nuxt/issues/20379

**Review by danielroe — COMMENTED** [review]
This PR is great! Thank you so much for the phenomenal work here.

Sorry to have just pushed changes - mostly a result of my lack of time.

If you have a chance to review, would you see if I've unwittingly undone something you set for a good reason? 🙏

**Comment by blowsie** [comment]
closes #934

**Comment by rdunk** [comment]
Think this is good to go pending documentation.

**Comment by rdunk** [comment]
Some minimal docs are up, I figured best to get this shipped and adjust and improve those accordingly. Let me know if you'd like them structured differently. Also snuck in a few last minute changes to the configuration based on some internal conversations. Ready for a final review!

(Can I leave merge/release up to you @danielroe?)

**Comment by danielroe** [comment]
Perfect!

**Comment by timbenniks** [comment]
Hey all, I'm super excited about this feature, when will there be a release to NPM in which I can use visual editing?

**Comment by danielroe** [comment]
There's a beta release at `@nuxtjs/sanity@beta` you can try out. There's currently a few niggles with Vite + the newer sanity dependencies that will require us to handle optimizeDeps (probably?)

**Comment by timbenniks** [comment]
You are correct. I just had a look with beta 1.9.0 but I can't get it to run.

I have this in my Nuxt config:
```
vite: {
  optimizeDeps: { exclude: ["parse-headers"] }
},
```

Screenshot 2024-03-09 at 22 31 33

**Comment by danielroe** [comment]
You probably need to _include_ it. But you will find a rabbit hole down there. If you get a chance and get something working, do let me know. One main issue is that in order for optimising deps with `shamefully-hoist=false`, they have to be explicitly installed. (And these are sub deps of sub deps which makes it a real pain.)

One avenue to explore is that this is not an issue in the module repository which suggests that something about the config (maybe another package being installed?) avoids the issue. But I need to make some time to investigate.

**Comment by timbenniks** [comment]
The deeper I dive, the weirder it gets! 

Screenshot 2024-03-10 at 11 33 23

I try this to see if i can get any further: https://www.sanity.io/docs/nuxt-loader

**Comment by rdunk** [comment]
@timbenniks Best not to go down the `@sanity/nuxt-loader` path! We will be deprecating that package in favour of this module as soon as we have a stable release.

**Comment by danielroe** [comment]
Released! Please do let me know if you encounter any niggles. 🙏

**Comment by timbenniks** [comment]
Hey all, using "@nuxtjs/sanity": "^1.10.1" I still get similar issues as described above. 
Screenshot 2024-03-30 at 12 30 44

**Comment by blowsie** [comment]
> Hey all, using "@nuxtjs/sanity": "^1.10.1" I still get similar issues as described above. Screenshot 2024-03-30 at 12 30 44

Im not familiar with the issue you are encountering, but this may help you get started
https://github.com/sanity-io/sanity-template-nuxt-clean

**Pull request merged**
