### PR TITLE
fix: send perspective as query param when using GET method

### PR DESCRIPTION
**Pull request by jesperbjerke**
This is the same issue as here: https://github.com/nuxt-modules/sanity/pull/930 but with GET queries. This appends perspective there as well.

### CODE REVIEW

**Review by danielroe — COMMENTED** [review]
Should we just move the query up into fetchOptions?

**Comment by jesperbjerke** [comment]
> Should we just move the query up into fetchOptions?

Hah, good point! Completely missed that 😅 Changed now

**Comment by jesperbjerke** [comment]
Noticed the RequestInit type doesn't allow for `query`. And changing it to FetchOptions didn't allow for `body` 🙃 
I'll see if I find the correct type to use..

**Review by danielroe — COMMENTED** [review]
Actually ... Maybe we need to add it to the `qs` as `&perspective=` rather than via `query` for the `get` request... Seems like it would produce a double query otherwise.

**Comment by jesperbjerke** [comment]
> Actually ... Maybe we need to add it to the `qs` as `&perspective=` rather than via `query` for the `get` request... Seems like it would produce a double query otherwise.

When I tested it just appended perspective to the existing query params and worked as expected. But I can double check again.
What do you mean with "double query" though? 🤔

**Comment by jesperbjerke** [comment]
Just tested again, both with and without defining perspective in my config. Looks to me as it behaves as expected and just appends the perspective to the existing query params. Perspective defaults to "raw" if not defined.

This is the query params it produces for me:
Screenshot 2024-05-31 at 14 56 33

```
data/query/staging?query=*%5B_type+==+%22article%22+%26%26+language+==+$language+%26%26+slug.current+==+$slug%5D%5B0%5D%7Btitle,+animal_type,+intro,+seo,+body,+image%7D&$language=%22en%22&$slug=%22invaertes-parasiter-hos-kanin-test%22&perspective=previewDrafts
```

**Review by danielroe — APPROVED** [review]
Thank you ❤️

**Pull request merged**
